# -*- coding: utf-8 -*-
"""Programming Assignment_1 (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/132arpiX0t3vJEHVrFj3C04hJXjuyk7tK

## Programming Assignment_1
-------------

### 1. Write a Python program to print "Hello Python"?
"""

print("Hello Python")

"""### 2. Write a Python program to do arithmetical operations addition and division.?

"""

A=int(input())
B=int(input())

#Addition

print(A+B)

#Division
print(A/B)

"""### 3. Write a Python program to find the area of a triangle?

"""

L=int(input())
B=int(input())
print(int(L*B/2))

"""### 4. Write a Python program to swap two variables?

"""

A=int(input())
B=int(input())
A=A+B
B=A-B
A=A-B
print(A)
print(B)

"""### 5. Write a Python program to generate a random number?

"""

import random
print(random.randint(0,100))